### ISSUE TITLE
How can I implement delegate viewForAnnotation?

### ISSUE THREAD

**Issue by lexrus** [RxSwiftCommunity/RxMKMapView#12]
I found the following delegate methods are not implemented in this extension:

``` swift
func mapView(mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView?
func mapView(mapView: MKMapView, rendererForOverlay overlay: MKOverlay) -> MKOverlayRenderer
```

How can I add a MKCircleRenderer to the map without this delegate?

**Comment by lexrus** [comment]
I've forwarded the delegate to get it work. But still wondering if there's other RxSwiftish way.

``` swift
mapView.rx_delegate
    .setForwardToDelegate(NativeMapViewDelegate(), retainDelegate: true)
```

**Comment by whisper-bye** [comment]
+1
@lexrus Did you solve this problem?

**Comment by lexrus** [comment]
@whisper-bye Removed this lib and code in the Apple way. 😭

**Comment by whisper-bye** [comment]
@lexrus that's good 😭

**Comment by mkko** [comment]
I guess this is not an issue anymore, so closing.

**Comment by jdmoreira** [comment]
Humm... I'm wondering the same

Seems like a reasonable thing for `viewForAnnotation` to be somehow handled through RxMKMapView. anyone has tips on how to approach this?
