### ISSUE TITLE
Can't install with RxSwift 3.1.0

### ISSUE THREAD

**Issue by AYastrebov** [RxSwiftCommunity/RxMKMapView#17]
I am using cocoapods with RxSwift 3.1.0

trying to install latest pod version

pod 'RxMKMapView', '~> 3.0.0'

And getting error

[!] Unable to satisfy the following requirements:

- `RxMKMapView (~> 3.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `RxMKMapView (~> 3.0.0)`.

**Comment by freak4pc** [comment]
@AYastrebov I've submitted a PR to fix this
