### ISSUE TITLE
EXC_BAD_ACCESS with a project setup with Carthage, Xcode 9.4

### ISSUE THREAD

**Issue by mkko** [RxSwiftCommunity/RxMKMapView#34]
Don't know if it's just me, but I'm getting a crash when using Xcode 9.4 (9F1027a), Swift 4.1.2. Here's an example demonstrating the issue:

[https://github.com/mkko/RxMKMapViewCrash](https://github.com/mkko/RxMKMapViewCrash)

The issue is reproducible in simulator when building with Carthage. It seems that with CocoaPods everything's fine with same versions. I haven't tried manual setup yet.

There could be something I missed, but I've been using RxMKMapView without issues with Xcode 9.2 (9C40b), Swift 4.0.3. I'd be just happy to hear whether it is just me or if this issue is real.

Here's the stack trace of what I get:

<img width="719" alt="screen shot 2018-06-20 at 10 25 26" src="https://user-images.githubusercontent.com/142544/41644047-b2d2b67c-7475-11e8-937f-f5847f8df0b6.png">

**Comment by mkko** [comment]
Manual setup works fine, so there's something weird either with my machine or with the output generated by Carthage.

**Comment by freak4pc** [comment]
Unfortunately I have very little experience (or liking) with Carthage so I will be of little help. If you find the issue and want to submit a PR, I'd love to take a look and merge. Thanks !

**Comment by mkko** [comment]
@freak4pc Do you have the chance to try out if the crash is real? It's simply a matter initialising the project from the command line with `carthage bootsrap` and then running the project.

I'm happy to try to figure out what's wrong here, just not sure how. I'm guessing Carthage build produces somehow messed up binaries, so I guess I'll start figuring out what's different there.

**Comment by mkko** [comment]
I think I've figured the reason for the issue. From what it looks like Carthage mistakenly builds the example app (the actual framework included) instead of the actual framework. It could be some automatic behavior prioritizing Xcode workspace files over project files, I still need to check this.

I also don't know what actually gets messed up with the built framework, but I guess it doesn't matter since the problem is kind of obvious now.

I'll continue on this to find some clean solution.

**Comment by mkko** [comment]
Okay, so this is intended behavior with Carthage; it prefers `.xcworkspace` files over `.xcodeproj`. I think the only option here is to include a workspace file on the root level.

[Here](https://github.com/Carthage/Carthage/issues/1974)'s a discussion on similar issue with RxSwift and Carthage.

**Comment by freak4pc** [comment]
Gotya. A tad weird but if that's the case we can go with it. 

I think It'd be best to add a xcworkspace build thing as well as a Carthage build to make sure its always possible to build. (or at least the former). What do you think? 

https://github.com/RxSwiftCommunity/RxMKMapView/blob/master/circle.yml

**Comment by mkko** [comment]
Agreed, I already answered in the PR. Sadly no clean way around this, so that's our only option.

**Comment by freak4pc** [comment]
Fixed in #35
