### ISSUE TITLE
mapView: viewFor: MKAnnotation not getting called

### ISSUE THREAD

**Issue by jbmaxwell** [RxSwiftCommunity/RxMKMapView#36]
It seems that `(_ mapView: MKMapView viewFor: MKAnnotation) -> MKAnnotationView?` isn't implemented, but I'm also noticing that it isn't getting called on my viewController. I realize this may not be a problem in RxMKMapView, but any theories as to why it's not getting called in my case? Several other RxMKMapView delegate methods (e.g., regionDidChangeAnimated) are getting called, as expected.

**Comment by freak4pc** [comment]
Hey - Seems like the example project does this and it works, please look at the code there and try out :) If it works there and specifically doesn't work for you, this isn't really a bug with the repo. 

https://github.com/RxSwiftCommunity/RxMKMapView/blob/master/Example/RxMKMapView/ViewController.swift#L152

**Comment by freak4pc** [comment]
Are you setting a forward delegate though? 

https://github.com/RxSwiftCommunity/RxMKMapView/blob/f0b686894541a3710d5654e3d2df067c7ebaacf3/Example/RxMKMapView/ViewController.swift#L79-L83

**Comment by jbmaxwell** [comment]
Ha! Wow, that is so bizarre. I don't know how many times I looked at that and didn't see the setDelegate... ugh. Thanks!
