### ISSUE TITLE
rx_didChangeState Throws

### ISSUE THREAD

**Issue by morgz** [RxSwiftCommunity/RxMKMapView#4]
Just a heads up that this method throws with a casting error. Looking into figuring it out!

**Comment by morgz** [comment]
Seems to be an issue with MKAnnotationViewDragState. It is trying to cast UIInt to MKAnnotationViewDragState. MKAnnotationViewDragState is an enum so it isn't working.

Need something along the lines of:

```
            return (view: try castOrThrow(MKAnnotationView.self, a[1]),
                newState: MKAnnotationViewDragState(rawValue:try castOrThrow(UInt.self, a[2])),
                oldState: MKAnnotationViewDragState(rawValue:try castOrThrow(UInt.self, a[3])))
```

But can't get that to compile at the mo...

**Comment by sergdort** [comment]
Hi, @morgz it should be fixed now
