### ISSUE TITLE
Will crash On ios11.4.1

### ISSUE THREAD

**Issue by CtrlJone** [RxSwiftCommunity/RxMKMapView#40]
xcode 10.1
**ios 11.4.1**
![image](https://user-images.githubusercontent.com/8390188/48547664-2420b900-e906-11e8-8575-1acb3f885455.png)
Only if the system is 11.4.1 on the phone, other systems are good
I don't know what went wrong, I hope the author can tell me how to fix it
thankyou

**Comment by mkko** [comment]
What is the exact error/crash you're seeing? Have you tried the provided example with the same environment?

I don't think the error is in the lines you pasted, but if the example app doesn't crash on iOS 11.4.1, can you provide a minified example that produces that crash? I'll gladly to look into this, just right now I don't have enough Internet to download the old version of the simulator.

**Comment by CtrlJone** [comment]
Thank you for your reply. This is a problem in the case of real machine
Only when the map is moved will it crash
![image](https://user-images.githubusercontent.com/8390188/48590884-34737b00-e97c-11e8-91e3-9408e6dbd036.png)
If I comment out the code, it won't crash
It's going to look something like this
![image](https://user-images.githubusercontent.com/8390188/48590919-6c7abe00-e97c-11e8-96e9-abcba60b0ce2.png)
I've changed a couple of different ways of writing the same thing, but on a phone with ios 11.4.1 real phone system it crashes
I don't know why this is happening and hopefully it can be fixed
thankyou

**Comment by CtrlJone** [comment]
Sorry to bother you, but I think I've solved this problem. It's a bug in the Apple system. Thank you for answering my questions.
