### ISSUE TITLE
When will RxMKMapView support Swift 5?

### ISSUE THREAD

**Issue by CtrlJone** [RxSwiftCommunity/RxMKMapView#44]
RxSwift already released its version to support Swift 5. When will RxMKMapView support Swift 5? We are encountering compatibility issues already related to Swift 5 migration. Thanks!

**Comment by freak4pc** [comment]
Feel free to open a PR making the migration. I don’t mind reviewing it.

**Comment by CtrlJone** [comment]
please thank you

**Comment by CtrlJone** [comment]
how can i do?

**Comment by freak4pc** [comment]
RxMKMapView 5.0 has been released.
