### ISSUE TITLE
Xcode 14 Beta Build Failed

### ISSUE THREAD

**Issue by carbonimax** [RxSwiftCommunity/RxMKMapView#57]
### Stacktrace & log output
RxMKMapView/Sources/MKMapView+Rx.swift:174:14: error: type of expression is ambiguous without more context

**Comment by freak4pc** [comment]
This is a Swift / Xcode 14.4 bug, unfortunately. See here:
https://github.com/apple/swift/issues/45652

**Comment by mikelrob** [comment]
check out #58 🙏

**Comment by skydivedan** [comment]
The RC of Xcode 14 is out, and it still has this error.

**Comment by SentoCrespo** [comment]
Please update :)

**Comment by alexeyhatkevich** [comment]
Xcode Version 14.0 (14A309)
issue still exists
<img width="1016" alt="Screenshot 2022-09-14 at 12 06 00" src="https://user-images.githubusercontent.com/1841719/190126275-56c8b65e-9799-4d53-b9a4-bfb02ddff057.png">
<img width="1018" alt="Screenshot 2022-09-14 at 12 06 41" src="https://user-images.githubusercontent.com/1841719/190126300-98e75ff7-8b18-44aa-885d-17190961dcb0.png">

**Comment by freak4pc** [comment]
Should be fixed in 6.0.1 Thanks @mikelrob !
